/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.sql.SQLException;

/**
 *
 * @author Ivan De la Rosa
 */
public class FormMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMenu.class.getName());

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Alumnos_bt = new javax.swing.JButton();
        Secretarios_bt = new javax.swing.JButton();
        Volver_bt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Generación de boletas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Menú principal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        Alumnos_bt.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        Alumnos_bt.setText("Altas alumnos");
        Alumnos_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alumnos_btActionPerformed(evt);
            }
        });
        getContentPane().add(Alumnos_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 30));

        Secretarios_bt.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        Secretarios_bt.setText("Altas secretarios");
        Secretarios_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Secretarios_btActionPerformed(evt);
            }
        });
        getContentPane().add(Secretarios_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 30));

        Volver_bt.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        Volver_bt.setText("Cerrar sesión");
        Volver_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_btActionPerformed(evt);
            }
        });
        getContentPane().add(Volver_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/destiny.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 506));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Alumnos_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alumnos_btActionPerformed
        FormAlumnos ObjAlumnos = new FormAlumnos();
        ObjAlumnos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Alumnos_btActionPerformed

    private void Secretarios_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Secretarios_btActionPerformed
        FormSecretarios ObjFormSecretarios = new FormSecretarios();
        ObjFormSecretarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Secretarios_btActionPerformed

    private void Volver_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_btActionPerformed
        FormLogin ObjFormLogin = new FormLogin();
        ObjFormLogin.setVisible(true);
        
        try 
        {
            FormLogin.conexionGlobal.IniciarConexion().close();
        } 
        catch (SQLException ex) 
        {
            System.getLogger(FormMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_Volver_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alumnos_bt;
    private javax.swing.JButton Secretarios_bt;
    private javax.swing.JButton Volver_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
