/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.SecretarioControlador;
import javax.swing.JOptionPane;
/**
 *
 * @author Ivan De la Rosa
 */
public class FormSecretarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSecretarios.class.getName());
    private FormMenu FormMenu;
    
    /**
     * Creates new form FormSecretarios
     */
    public FormSecretarios() 
    {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        SecretarioControlador ObjSecretarioControlador = new SecretarioControlador();
        if (FormLogin.conexionGlobal != null && FormLogin.conexionGlobal.ValidarConexion()) 
        {
            ObjSecretarioControlador.MostrarSecretario(FormLogin.conexionGlobal.IniciarConexion(), Secretarios_tabla);
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "No se pudo cargar datos.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ID_tb = new javax.swing.JTextField();
        Nombre_tb = new javax.swing.JTextField();
        Apellido_tb = new javax.swing.JTextField();
        Clave_tb = new javax.swing.JTextField();
        Usuario_tb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Secretarios_tabla = new javax.swing.JTable();
        Insertar_bt = new javax.swing.JButton();
        Modificar_bt = new javax.swing.JButton();
        Eliminar_bt = new javax.swing.JButton();
        Volver_bt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secretarios");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Secretario");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Apellido");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Usuario");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Contraseña");

        ID_tb.setEditable(false);

        Secretarios_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Secretarios_tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Secretarios_tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Secretarios_tabla);

        Insertar_bt.setText("Insertar");
        Insertar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insertar_btActionPerformed(evt);
            }
        });

        Modificar_bt.setText("Modificar");
        Modificar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_btActionPerformed(evt);
            }
        });

        Eliminar_bt.setText("Eliminar");
        Eliminar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_btActionPerformed(evt);
            }
        });

        Volver_bt.setText("Volver");
        Volver_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellido_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Modificar_bt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eliminar_bt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Insertar_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Usuario_tb)
                            .addComponent(Clave_tb)))
                    .addComponent(Volver_bt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ID_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Nombre_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Apellido_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Usuario_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Clave_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(Insertar_bt)
                        .addGap(18, 18, 18)
                        .addComponent(Modificar_bt)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar_bt)
                        .addGap(18, 18, 18)
                        .addComponent(Volver_bt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setFormMenu(FormMenu FormMenu)
    {
        this.FormMenu = FormMenu;
    }
    
    private void Secretarios_tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Secretarios_tablaMouseClicked
        SecretarioControlador ObjSecretarioControlador = new SecretarioControlador();
        ObjSecretarioControlador.SeleccionarSecretario(ID_tb, Nombre_tb, Apellido_tb, Usuario_tb, Clave_tb, Secretarios_tabla);
    }//GEN-LAST:event_Secretarios_tablaMouseClicked

    private void Insertar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insertar_btActionPerformed
        SecretarioControlador ObjSecretarioControlador = new SecretarioControlador();
        ObjSecretarioControlador.MaximoSecretario(FormLogin.conexionGlobal.IniciarConexion(), Nombre_tb, Apellido_tb, Usuario_tb, Clave_tb);
        ObjSecretarioControlador.MostrarSecretario(FormLogin.conexionGlobal.IniciarConexion(), Secretarios_tabla);
    }//GEN-LAST:event_Insertar_btActionPerformed

    private void Modificar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_btActionPerformed
        SecretarioControlador ObjSecretarioControlador = new SecretarioControlador();
        ObjSecretarioControlador.ModificarSecretario(FormLogin.conexionGlobal.IniciarConexion(), ID_tb, Nombre_tb, Apellido_tb, Usuario_tb, Clave_tb);
        ObjSecretarioControlador.MostrarSecretario(FormLogin.conexionGlobal.IniciarConexion(), Secretarios_tabla);
    }//GEN-LAST:event_Modificar_btActionPerformed

    private void Eliminar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_btActionPerformed
        SecretarioControlador ObjSecretarioControlador = new SecretarioControlador();
        ObjSecretarioControlador.EliminarSecretario(FormLogin.conexionGlobal.IniciarConexion(), ID_tb);
        ObjSecretarioControlador.MostrarSecretario(FormLogin.conexionGlobal.IniciarConexion(), Secretarios_tabla);
    }//GEN-LAST:event_Eliminar_btActionPerformed

    private void Volver_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_btActionPerformed
        FormMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Volver_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormSecretarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido_tb;
    private javax.swing.JTextField Clave_tb;
    private javax.swing.JButton Eliminar_bt;
    private javax.swing.JTextField ID_tb;
    private javax.swing.JButton Insertar_bt;
    private javax.swing.JButton Modificar_bt;
    private javax.swing.JTextField Nombre_tb;
    private javax.swing.JTable Secretarios_tabla;
    private javax.swing.JTextField Usuario_tb;
    private javax.swing.JButton Volver_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
