/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.EnviarCorreoControlador;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Ivan De la Rosa
 */
public class FormEnviarCorreo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormEnviarCorreo.class.getName());
    private FormEnviarBoletas FormEnviarBoletas;
    private File archivoAdjunto;
    
    /**
     * Creates new form FormEnviarCorreo
     */
    public FormEnviarCorreo() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.archivoAdjunto = null;
    }
    
    public void setFormEnviarBoletas(FormEnviarBoletas FormEnviarBoletas)
    {
        this.FormEnviarBoletas = FormEnviarBoletas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Destinatario_tb = new javax.swing.JTextField();
        Asunto_tb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Contenido_ta = new javax.swing.JTextArea();
        Enviar_bt = new javax.swing.JButton();
        Adjuntar_bt = new javax.swing.JButton();
        Nombre_archivo_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Enviar Correo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Destinatario:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Asunto:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Contenido:");

        Contenido_ta.setColumns(20);
        Contenido_ta.setRows(5);
        jScrollPane1.setViewportView(Contenido_ta);

        Enviar_bt.setText("Enviar");
        Enviar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enviar_btActionPerformed(evt);
            }
        });

        Adjuntar_bt.setText("Adjuntar archivo");
        Adjuntar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adjuntar_btActionPerformed(evt);
            }
        });

        Nombre_archivo_lb.setText("Sin archivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Adjuntar_bt)
                        .addGap(46, 46, 46)
                        .addComponent(Enviar_bt)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nombre_archivo_lb)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Destinatario_tb)
                            .addComponent(Asunto_tb)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Destinatario_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Asunto_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Nombre_archivo_lb)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enviar_bt)
                    .addComponent(Adjuntar_bt))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Enviar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enviar_btActionPerformed
        EnviarCorreoControlador ObjEnviarCorreoControlador = new EnviarCorreoControlador();
    
        // Se pasa el archivo adjunto (puede ser null si no se seleccionó nada)
        ObjEnviarCorreoControlador.createEmail(Destinatario_tb, Asunto_tb, Contenido_ta, this.archivoAdjunto);
        ObjEnviarCorreoControlador.sendEmail();

        // Limpiar selección después de enviar
        this.archivoAdjunto = null;
        this.Nombre_archivo_lb.setText("Sin archivo");
    }//GEN-LAST:event_Enviar_btActionPerformed

    private void Adjuntar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adjuntar_btActionPerformed
        JFileChooser fileChooser = new JFileChooser();
    
        // Obtener la ruta del proyecto
        String userDir = System.getProperty("user.dir");
        // Establecer la carpeta "Reportes"
        File reportesDir = new File(userDir, "Reportes");

        // Crear la carpeta si no existe
        if (!reportesDir.exists()) {
            reportesDir.mkdirs();
        }

        // Configurar el JFileChooser
        fileChooser.setCurrentDirectory(reportesDir);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Seleccionar archivo");

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            // El usuario seleccionó un archivo
            this.archivoAdjunto = fileChooser.getSelectedFile();
            // Actualizar el label
            Nombre_archivo_lb.setText(this.archivoAdjunto.getName());
        } else {
            // El usuario canceló
            this.archivoAdjunto = null;
            Nombre_archivo_lb.setText("Sin archivo");
        }
    }//GEN-LAST:event_Adjuntar_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormEnviarCorreo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adjuntar_bt;
    private javax.swing.JTextField Asunto_tb;
    private javax.swing.JTextArea Contenido_ta;
    private javax.swing.JTextField Destinatario_tb;
    private javax.swing.JButton Enviar_bt;
    private javax.swing.JLabel Nombre_archivo_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
