/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.RespaldoControlador;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Ivan De la Rosa
 */
public class FormRespaldo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRespaldo.class.getName());
    private FormMenu FormMenu;
    
    private RespaldoControlador respaldoControlador;
    
    /**
     * Creates new form FormRespaldo
     */
    public FormRespaldo() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.respaldoControlador = new RespaldoControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Respaldo_bt = new javax.swing.JButton();
        Clave_tb = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Respaldo_bt.setText("Crear respaldo");
        Respaldo_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Respaldo_btActionPerformed(evt);
            }
        });

        jLabel1.setText("Escriba la contraseña de usuario administrador:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Respaldo_bt)
                            .addComponent(Clave_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(Clave_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Respaldo_bt)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Respaldo_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Respaldo_btActionPerformed
        // --- CAMBIO 1: LEER LA CONTRASEÑA ---
        char[] passwordChars = Clave_tb.getPassword();
        final String password = new String(passwordChars);

        // --- CAMBIO 2: VALIDAR LA CONTRASEÑA ---
        if (password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, ingrese la contraseña de la base de datos.",
                    "Contraseña Requerida",
                    JOptionPane.WARNING_MESSAGE);
            return; // Detiene la ejecución si no hay contraseña
        }

        // --- CAMBIO 3: LIMPIAR EL ARRAY (Buena práctica de seguridad) ---
        Arrays.fill(passwordChars, ' ');
        
        Respaldo_bt.setEnabled(false);
        Respaldo_bt.setText("Ejecutando Respaldo...");

        // SwingWorker ejecuta la tarea pesada en un hilo separado
        SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            
            /**
             * Tarea de fondo: Llama al controlador (esto no congela la UI)
             */
            @Override
            protected String doInBackground() throws Exception {
                // --- CAMBIO 4: PASAR LA CONTRASEÑA AL CONTROLADOR ---
                return respaldoControlador.crearYEjecutarRespaldo(password);
            }

            /**
             * Tarea final: Se ejecuta cuando doInBackground() termina
             * (esto sí corre en el hilo de la UI)
             */
            @Override
            protected void done() {
                try {
                    get(); 
                    JOptionPane.showMessageDialog(FormRespaldo.this,
                            "Respaldo completado con éxito.",
                            "Tarea Finalizada",
                            JOptionPane.INFORMATION_MESSAGE);
                    
                } catch (Exception e) {
                    e.printStackTrace(); 
                    
                    // --- CAMBIO 5: MEJOR MENSAJE DE ERROR DE CONTRASEÑA ---
                    String errorMsg = e.getMessage();
                    if (errorMsg != null && errorMsg.contains("contraseña es incorrecta")) {
                         JOptionPane.showMessageDialog(FormRespaldo.this,
                            "Error: La contraseña de la base de datos es incorrecta.",
                            "Error de Autenticación",
                            JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(FormRespaldo.this,
                            "Ocurrió un error durante el respaldo.\n" + e.getMessage(),
                            "Error de Ejecución",
                            JOptionPane.ERROR_MESSAGE);
                    }
                }
                
                // 4. Reactivar el botón, sin importar si hubo éxito o error
                Respaldo_bt.setEnabled(true);
                Respaldo_bt.setText("Crear y Ejecutar Respaldo");
                
                // --- CAMBIO 6: LIMPIAR EL CAMPO DE CONTRASEÑA ---
                Clave_tb.setText("");
            }
        };
        
        // Inicia el worker (el proceso en segundo plano)
        worker.execute();
    }//GEN-LAST:event_Respaldo_btActionPerformed

    public void setFormMenu(FormMenu FormMenu)
    {
        this.FormMenu = FormMenu;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRespaldo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Clave_tb;
    private javax.swing.JButton Respaldo_bt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
