/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package vistas;
import java.sql.SQLException;
import static vistas.FormLogin.conexionGlobal;

/**
 *
 * @author Benny Brian
 */
public class FromMenuSecre extends javax.swing.JPanel implements java.beans.Customizer {
      private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FromMenuSecre.class.getName());
    private FormLogin FormLogin;
    //private Object bean;

    /**
     * Creates new customizer NewCustomizer
     */
    public FromMenuSecre() {
        initComponents();
    }
    
    public void setObject(Object bean) {
      //  this.bean = bean;
    }
    
    public void setFormLogin(FormLogin FormLogin)
    {
        this.FormLogin = FormLogin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Alumnos_bt = new javax.swing.JButton();
        Generar_bt = new javax.swing.JButton();
        Datos_Estadisticos_ = new javax.swing.JButton();
        Lista_Trimestral = new javax.swing.JButton();
        Volver_bt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ESC. PRIM. Arcoiris");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 470, 40));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 30)); // NOI18N
        jLabel2.setText("Menu Principal");
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 230, 70));

        Alumnos_bt.setBackground(new java.awt.Color(204, 204, 204));
        Alumnos_bt.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        Alumnos_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_alumnos.png"))); // NOI18N
        Alumnos_bt.setToolTipText("");
        Alumnos_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alumnos_btActionPerformed(evt);
            }
        });
        add(Alumnos_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 160, 130));

        Generar_bt.setBackground(new java.awt.Color(204, 204, 204));
        Generar_bt.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        Generar_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_boletas(1).png"))); // NOI18N
        Generar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generar_btActionPerformed(evt);
            }
        });
        add(Generar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 160, 130));

        Datos_Estadisticos_.setBackground(new java.awt.Color(204, 204, 204));
        Datos_Estadisticos_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_datos.png"))); // NOI18N
        add(Datos_Estadisticos_, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 160, 130));

        Lista_Trimestral.setBackground(new java.awt.Color(204, 204, 204));
        Lista_Trimestral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_lisTri.png"))); // NOI18N
        Lista_Trimestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_TrimestralActionPerformed(evt);
            }
        });
        add(Lista_Trimestral, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 160, 130));

        Volver_bt.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        Volver_bt.setText("Cerrar sesión");
        Volver_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_btActionPerformed(evt);
            }
        });
        add(Volver_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_menu2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 900, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void Alumnos_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alumnos_btActionPerformed
        
    }//GEN-LAST:event_Alumnos_btActionPerformed

    private void Generar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generar_btActionPerformed
        
    }//GEN-LAST:event_Generar_btActionPerformed

    private void Lista_TrimestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_TrimestralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lista_TrimestralActionPerformed

    private void Volver_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_btActionPerformed
      FormLogin.setVisible(true);
        
        try 
        {
            FormLogin.conexionGlobal.IniciarConexion().close();
        } 
        catch (SQLException ex) 
        {
            System.getLogger(FormMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_Volver_btActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Alumnos_bt;
    public javax.swing.JButton Datos_Estadisticos_;
    public javax.swing.JButton Generar_bt;
    public javax.swing.JButton Lista_Trimestral;
    public javax.swing.JButton Volver_bt;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
